# Generated by Django 3.2 on 2023-04-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.CharField(max_length=250)),
                ('pros', models.CharField(max_length=250)),
                ('cons', models.CharField(max_length=250)),
                ('conclusion', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movie_review',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Ott',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='moviecast',
            options={'verbose_name': 'Movie Cast', 'verbose_name_plural': 'Movie Casts'},
        ),
        migrations.AlterModelOptions(
            name='movielanguage',
            options={'managed': False, 'verbose_name': 'Movie Language', 'verbose_name_plural': 'Movie Languages'},
        ),
        migrations.AlterModelOptions(
            name='movieott',
            options={'managed': False, 'verbose_name': 'Movie on OTT Platform', 'verbose_name_plural': 'Movies on OTT Platforms'},
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie_meta',
        ),
        migrations.AlterModelTable(
            name='movielanguage',
            table='movie_language',
        ),
        migrations.AlterModelTable(
            name='movieott',
            table='movie_ott',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
