# Generated by Django 3.2 on 2023-04-23 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230422_0308'),
    ]

    operations = [
       
    ]
