# Generated by Django 3.2 on 2023-07-17 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230517_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('director', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('total_episodes', models.IntegerField()),
                ('poster_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_series_meta',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='moviecast',
            table='movie_cast',
        ),
    ]
