# Generated by Django 4.0 on 2023-04-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
