# Generated by Django 3.2 on 2023-04-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movielanguage',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieott',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MoviesReview',
        ),
        migrations.DeleteModel(
            name='Ott',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MovieLanguage',
        ),
        migrations.DeleteModel(
            name='MovieOtt',
        ),
    ]
